config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#home'
  resources :categories do 
    resources :products do
      collection do
        match 'search' => 'prdocuts#search', via: [:get, :post], as: :search
      end
    end
  end

  namespace :admin do
    resources :categories
    get "/dashboard", to: 'dashboard#index'
  end

  namespace :seller do
    resources :products
    get "/dashboard", to: 'dashboard#index'
    get "/dashboard/orders", to: 'dashboard#show'
  end
  get '/search', to: 'products#index'
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end

  resources :order_items, only: %i(create update destroy)
  resources :orders, only: %i(create show index)
  get '/cart', to: 'cart#show'

  get '/users/:username', to: 'profile#show', as: 'user'

  delete '/empty_cart', to: 'order_items#destroy_all'

  resources :reviews, only: %i(create edit update destroy) 
   
  post 'reviews_from_email', to: 'reviews#create_from_email'
  get '/reviews', to: 'reviews#new'

  mount Sidekiq::Web => '/sidekiq'


end

app/views/partials/_footer.html.slim
.container-fluid.bg-secondary.text-dark.mt-5.pt-5
    .row.px-xl-5.pt-5
        .col-lg-4.col-md-12.mb-5.pr-3.pr-xl-5
            a.text-decoration-none.d-block href = root_path
                h1.m-0.display-5.font-weight-semi-bold
                    span.text-primary.font-weight-bold Shop
                    | App
            p.mb-2 
            p.mb-2
            p.mb-8

        .col-lg-8.col-md-12
            .row
                .col-md-4.mb-5
                    .font-weight-bold.text-dark.mb-4
                        | Quick links
                    .d-flex.flex-column.justify-content-start
                        a.text-dark.mb-2 href = root_path
                            i.fa.fa-angle-right.mr-2
                            | Home
                        a.text-dark.mb-2 href = categories_path
                            i.fa.fa-angle-right.mr-2
                            | Categories
                .col-md-4.mb-5
                    .font-weight-bold.text-dark.mb-4
                        | Quick links
                    .d-flex.flex-column.justify-content-start
                        a.text-dark.mb-2 href = root_path
                            i.fa.fa-angle-right.mr-2
                            | Home
                        a.text-dark.mb-2 href = categories_path
                            i.fa.fa-angle-right.mr-2
                            | Categories
                .col-md-4.mb-5
                    .font-weight-bold.text-dark.mb-4
                        | Newsletter
                    form
                        .form-group
                            input type="text" placeholder="Your Name" class="form-control border-0 py-4"
                        .form-group
                            input type="text" placeholder="Your Email" class="form-control border-0 py-4"
                        div
                            button type="submit" class="btn btn-primary btn-block border-0 py-3"
                                | Submit
    .row.border-top.border-light.mx-xl-5.py-4
        .col-md-6.px-xl-0

        .mb-md-0.text-center.text-md-left.text-dark

app/views/partials/_modal.html.slim
#overlay
#modal
  #content
    | No JavaScript Yet!
  a#close href="#"
    | close

app/views/partials/_nav.html.slim
.container-fluid.nav-top  
    .row.align-items-center.py-3.px-xl-5
        .col-lg-2.d-none.d-lg-block
            a.text-decoration-none href = root_url
                h1.m-0.display-5.font-weight-semi-bold
                    span.text-primary.font-weight-bold Shop
                    span.text-secondary App

        .col-lg-3.d-none.d-lg-block
            .d-flex.mr-auto.py-0
                = link_to "Home", root_path, class: "nav-item nav-link"
                a.collapsed.nav-item.nav-link data-toggle="collapse" href="#navbar-vertical"
                    | Categories
                    i.fa.fa-angle-down.ml-2
                nav.position-absolute.navbar.navbar-vertical.navbar-light.align-items-start.p-0.border.border-top-0.border-bottom-0.bg-light.collapse#navbar-vertical style="width: calc(100% - 30px); z-index: 1; top: 72px;"
                    .navbar-nav.w-100.overflow-hidden
                        = link_to "All categories", categories_path, class: "nav-item nav-link"
                        - @categoies_nav.each do |category|
                            = link_to category.name, category_products_path(category), class: "nav-item nav-link"
                                        
                            
        .col-lg-4.col-8.text-left
            = search_form_for @q, url: search_products_path, remote: true do |f|
                .input-group
                    = f.text_field :title_or_description_cont, id: :query, class: "form-control", placeholder: "Search for a product"
                    .input-group-append
                        .input-group-text.bg-transparent.text-primary
                            = f.button :submit, id: :search, class:"search-btn"
                                i.fa.fa-magnifying-glass
        .col-lg-2.col-2.d-flex.m1-auto.p-0.align-items-start
            - unless user_signed_in?
                = link_to "Sign in", new_user_session_path, class: "nav-item nav-link"
                = link_to "Sign up", new_user_registration_path, class: "nav-item nav-link"
            - else
                .dropdown.nav-item.d-flex.align-self-start.m-2
                    a.nav-link.dropdown-toggle href="#" data-toggle="dropdown" 
                        - if current_user.profile_picture.attached?
                            image.profile-picture.mr-lg-3 src = url_for(current_user.profile_picture)
                        - else
                            = image_tag "images.png", class: "profile-picture mr-lg-3"
                        span.text.d-none.d-xl-inline = current_user.first_name if current_user.first_name.present?
                    .dropdown-menu.rounded-0.m-0.position-absolute
                        = link_to "Profile", user_path(current_user.username), class: "dropdown-item" 
                        - if user_signed_in? 
                            -if current_user.has_role? :admin
                                = link_to 'Admin Dashboard', admin_dashboard_path, class: "dropdown-item"  
                            - if current_user.has_role? :seller or current_user.has_role? :admin
                                = link_to 'Dashboard', seller_dashboard_path, class: "dropdown-item"
                            - if current_user.has_role? :buyer or current_user.has_role? :admin
                                = link_to "My orders", orders_path, class:"dropdown-item"
                        = link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"
        .col-lg-1.col-2.text-right
            .btn
                = link_to cart_path do
                    i.fa.fa-shopping-cart.text-primary
                    #cart = render "cart/partials/cart"
.container-fluid.mb-2            
    .row.border-top.px-xl-5    
            
        .col-lg-12
            nav.navbar.navbar-expand-lg.bg-light.navbar-light.py-3.py-lg-0.px-0 
                a.text-decoration-none.d-block.d-lg-none href = root_path
                    h1.m-0.display-5.font-weight-semi-bold
                        span.text-primary.font-weight-bold Shop
                        span.text-secondary App
                button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#navbarCollapsed" aria-expanded="false"
                    span.navbar-toggler-icon
                div.d-md-none.justify-content-between.collapse.w-100#navbarCollapsed
                    = link_to "Home", root_path, class: "nav-item nav-link"
                    a.nav-item.nav-link data-toggle="collapse" data-target="#navbar-vertical" aria-controls="navbar-vertical"
                        | Categories
                        i.fa.fa-angle-down.ml-2
                    div.collapse.navbar.navbar-vertical.navbar-light.align-items-start.p-0.border.border-top-0.border-bottom-0.bg-light#navbar-vertical
                        .navbar-nav.w-100.overflow-hidden
                            = link_to "All categories", categories_path, class: "nav-item nav-link"
                            - @categoies_nav.each do |category|
                                = link_to category.name, category_products_path(category), class: "nav-item nav-link"
                


app/views/partials/_pagination.html.slim
/ This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
/ calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
/ The link variable is set to a proc that returns the link tag.
/ Usage: link.call( page_number [, text [, extra_attributes_string ]])
- link = pagy_link_proc(@pagy)
.col-12.pb-1
  nav.pagy_nav.pagination role="navigation" aria-label="pager Page navigation"
    .pagination.justify-content-center.mb-3
      - if @pagy.prev
        span.page.prev ==> link.call(@pagy.prev, pagy_t('@pagy.nav.prev'), 'aria-label="previous"')
      - else
        span.page.prev.disabled ==> pagy_t('@pagy.nav.prev')

      - @pagy.series.each do |item|        # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
        - if item.is_a?(Integer)          # page link
          span.page ==> link.call(item)

        - elsif item.is_a?(String)        # current page
          span.page.current ==> item

        - elsif item == :gap              # page gap
          span.page.gap ==> pagy_t('@pagy.nav.gap')

      - if @pagy.next
        span.page.next == link.call(@pagy.next, pagy_t('@pagy.nav.next'), 'aria-label="next"')
      - else
        span.page.next.disabled == pagy_t('@pagy.nav.next')