config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#home'
  resources :categories do 
    resources :products do
      collection do
        match 'search' => 'prdocuts#search', via: [:get, :post], as: :search
      end
    end
  end

  namespace :admin do
    resources :categories
    get "/dashboard", to: 'dashboard#index'
  end

  namespace :seller do
    resources :products
    get "/dashboard", to: 'dashboard#index'
    get "/dashboard/orders", to: 'dashboard#show'
  end
  get '/search', to: 'products#index'
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end

  resources :order_items, only: %i(create update destroy)
  resources :orders, only: %i(create show index)
  get '/cart', to: 'cart#show'

  get '/users/:username', to: 'profile#show', as: 'user'

  delete '/empty_cart', to: 'order_items#destroy_all'

  resources :reviews, only: %i(create edit update destroy) 
   
  post 'reviews_from_email', to: 'reviews#create_from_email'
  get '/reviews', to: 'reviews#new'

  mount Sidekiq::Web => '/sidekiq'


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :authenticate_user!, only: [:create]
    error = 201
    def create
        # check order item belongs to user???
        @order_item = OrderItem.find_by(user_id: current_user.id, id: review_params[:order_item_id], reviewed_at: nil)
        if @order_item.nil? 
            flash[:error] = "Review failed"
            redirect_to(request.referrer || root_path) and return
        end
        @review =  Review.new(
            title: review_params[:title],
            body: review_params[:body],
            rating: review_params[:rating],
            reviewer: current_user,
            product: @order_item.product,
            order_item: @order_item
        )
        if @review.save!
            @order_item.reviewed_at = @review.created_at
            @order_item.save!
            flash[:notice] = "Review successfully created"
        else
            flash[:error] = "Review failed"
            error = 500
        end
    end

    def create_from_email
        # check order item belongs to user???
        @order_item = OrderItem.find_by(id: review_params[:order_item_id], reviewed_at: nil)
        jwt_data = JWT.decode review_params[:authorization_token], ENV['SECRET_KEY'], true, { algorithm: 'HS256'}
        user = User.find(jwt_data.first.first[1])
        if !user 
            flash[:alert] = "Unauthorized"

            redirect_to(root_url) and return
        end
        if @order_item.nil? 
            flash[:alert] = "Review failed"
            redirect_to(root_url) and return
        end
        @review =  Review.new(
            title: review_params[:title],
            body: review_params[:body],
            rating: review_params[:rating],
            reviewer: user,
            product: @order_item.product,
            order_item: @order_item
        )
        if @review.save!
            @order_item.reviewed_at = @review.created_at
            @order_item.save!
            flash[:notice] = "Review successfully created"
        else
            flash[:error] = "Review failed"
        end
        redirect_to product_url(@order_item.product)
    end
    
    def edit
        @review = current_user.reviews.find(params[:id])
        new_review = @review
    end

    def update 
        @review = current_user.reviews.find(params[:id])
        respond_to do |format|
            if @review.update(review_params.except(:dummy_variable))
                format.html { redirect_to(request.referrer) }
                flash[:notice] = "Review was successfully updated." 
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @review = current_user.reviews.find(params[:id])
        @review.destroy
        @review.order_item.update(reviewed_at: nil)
    end

    private

    def review_params
        params.require(:review).permit(:title, :body, :rating, :order_item_id, :authorization_token, :dummy_variable)
    end

    
end

app/views/reviews/partials/_form.html.slim
= form_for defined?(new_review) ? new_review : @review do |f|
    .field
        .review-title = f.label :title
        .review-title__field = f.text_field :title

    .field
        = f.label :rating   
    span.star-field 
        - (1..5).each do |r|
            = f.label dom_id(defined?(@order_item) ? @order_item : defined?(item) ? item : @review, r), :" ", class: "star star--on"
            a.hidden = f.radio_button :rating, r, id: "review_" + dom_id(defined?(@order_item) ? @order_item : defined?(item) ? item : @review, r), checked: r == 5, class:"star-rating"
    br
    = f.hidden_field :order_item_id, value: defined?(new_review) ? new_review.order_item_id : @review.order_item_id
    = f.hidden_field :dummy_variable, value: current_page?(controller: 'orders') || current_page?(controller:"orders", action: "show")

    .field
        .review-body = f.label :body
        .review-body__field = f.text_area :body
    br
    .field 
        = f.submit :create, value: "Submit", class: "btn btn-primary submit-review border-none"

app/views/reviews/partials/_head.html.slim
.preview-badge
    - if defined?(average_rating) 
        - (1..5).each do |r|
            - if average_rating >= r and (average_rating - (r-1)) > 0.7
                p.star.star--on 
            - elsif ((average_rating - (r-1)) <= 0.7 and (average_rating - (r-1)) > 0)  
                p.star.star--half
            - else 
                p.star.star--off
    span.average_rating 
        - if reviews
            = average_rating.round 2
            |  average rating based on 
            = review_count
            |  reviews 

app/views/reviews/partials/_review_widget.html.slim
.product-page__reviews.p-0
    .reviews-header.p-0
        - if defined?(new_review) && !new_review.nil?
            h2 Share your review with others
            .review-form.cards.pt-3.mt-3
                = render "reviews/partials/form", new_review: new_review
        - if defined?(@average_rating)
            h2.pt-5.mt-5 Product reviews
            .mb-3 = render "reviews/partials/head", reviews: @reviews, average_rating: @average_rating, review_count: review_count

    .reviews-body
        - if defined?(@reviews)      
            .review-items.p-0 = render "reviews/partials/reviews", reviews: @reviews

app/views/reviews/partials/_reviews.html.slim
- reviews.each do |review|

    div.review-items__item.cards.mt-0 {id = (review.id.to_s + review.reviewer.username.to_s)}
        .reviewer_name 
            h4 = review.reviewer.first_name
        .review_timestamp 
            = review.created_at.strftime("%Y/%m/%d at %H:%M")
        .review_rating 
            = render 'reviews/partials/stars', reviews: review.rating, dummy_variable: reviews
        strong.review_title = review.title 
        .review_content = review.body
        - if user_signed_in? && review.reviewer == current_user
            = link_to "Edit review ", edit_review_path(review), remote: true
            = link_to "Delete review", review_path(review), method: :delete, remote: true, data: { confirm: 'Are you sure?' }

    br 
.pagination 
    = sanitize pagy_nav(@pagy) if @pagy.pages > 1

app/views/reviews/partials/_stars.html.slim
.preview-badge
    - if reviews 
        - (1..5).each do |r|
            - if reviews >= r and (reviews - (r-1)) > 0.7
                p.star.star--on 
            - elsif ((reviews - (r-1)) <= 0.7 and (reviews - (r-1)) > 0)  
                p.star.star--half
            - else 
                p.star.star--off
    span.average_rating 
        |
        - if defined?(product_reviews_count) 
            = product_reviews_count
            |  reviews 
        - elsif defined?(dummy_variable) and defined?(reviews)
            |   
        - elsif defined?(review_count) 
            = @review_count
            |  reviews 