config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#home'
  resources :categories do 
    resources :products do
      collection do
        match 'search' => 'prdocuts#search', via: [:get, :post], as: :search
      end
    end
  end

  namespace :admin do
    resources :categories
    get "/dashboard", to: 'dashboard#index'
  end

  namespace :seller do
    resources :products
    get "/dashboard", to: 'dashboard#index'
    get "/dashboard/orders", to: 'dashboard#show'
  end
  get '/search', to: 'products#index'
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end

  resources :order_items, only: %i(create update destroy)
  resources :orders, only: %i(create show index)
  get '/cart', to: 'cart#show'

  get '/users/:username', to: 'profile#show', as: 'user'

  delete '/empty_cart', to: 'order_items#destroy_all'

  resources :reviews, only: %i(create edit update destroy) 
   
  post 'reviews_from_email', to: 'reviews#create_from_email'
  get '/reviews', to: 'reviews#new'

  mount Sidekiq::Web => '/sidekiq'


end

app/models/category.rb
class Category < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: %i(slugged history finders)
    has_many :product_categories
    has_many :products, through: :product_categories, dependent: :destroy
    has_one_attached :category_picture
    def should_generate_new_friendly_id? #will change the slug if the name changed
        name_changed?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
    before_action :set_category, only: [:show, :edit, :update, :destroy ]
    
    def new
        @category = Category.new
        authorize @category
    end
    def create
        @category = Category.new(category_params)
        @category.category_picture.attach(params[:category_picture])
        authorize @category
        respond_to do |format|
            if @category.save and current_user.has_role? :admin
              format.html { redirect_to category_products_url(@category), notice: "Category was successfully created." }
            else
              format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def edit
        authorize @category
    end

    def update
        authorize @category
        respond_to do |format|
            if @category.update(category_params) and current_user.has_role? :admin
              format.html { redirect_to category_products_url(@category), notice: "Category was successfully created." }
            else
              format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        authorize @category
        @category.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "Category was successfully destroyed." }
        end
    end
    
    private
    def set_category
        @category = Category.friendly.find(params[:id])
    end
    def category_params
        params.require(:category).permit(:name, :category_picture)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.friendly.order(:name)
  end
  def home
    @categories = Category.last(4)
    @home_page = "home"
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/home.html.slim
.collection
    - @categories.each do |category|
        - if category.products.published.length > 0
            h2.page-title = category.name 
            .collection__products.home-cards__grid.row
                - category.products.published.last(5).sort_by(&:title).each do |product|
                    .col-lg-2.col-md-6.col-sm-12.pb-1
                        .card.product-item.border-0.mb-4
                            = link_to defined?(@category) ? category_product_path(params[:category_id], id: product.slug) : product_path(id: product.slug) do
                                .card-header.product-img.position-relative.overflow-hidden.bg-transparent.border-bottom.p-0
                                    - if product.product_picture.attached?
                                        image.img-fluid.w-100.p-4 src = url_for(product.product_picture)
                                    - else
                                        = image_tag "images.png", class: "img-fluid w-100 p-4 "
                                .card-body.text-center.p-0.pt-2.pb-1
                                    = product.title
                                    .vendor-name = product.seller.first_name
                                    - if product.reviews.count > 0
                                        = render 'reviews/partials/stars',
                                        product_reviews_count: product.reviews.count,
                                        reviews: product.reviews.collect { |review| review.rating }.sum / product.reviews.count.to_f
                                    - else
                                        .invisible preview-badge
                                    .d-flex.justify-content-center.product-price
                                            = number_to_currency product.price
                            .card-footer.d-flex.justify-content-center.bg-light.border-top
                                = render "products/shared/order", product: product
= javascript_pack_tag "cart_quantity"

app/views/categories/index.html.slim
h1.page-title.mb-5 Categories
.container-fluid
    .row.px-xl-5.pb-3
        - @categories.each do |category|
            .col-lg-4.col-md-6.pb-1 
                .cat-item.d-flex.flex-column.border.card.mb-4
                    = link_to category_products_path(category.slug) do
                        - if category.category_picture.attached?
                            .cat-img.position-relative.overflow-hidden.mb-3
                                image.img-fluid src = url_for(category.category_picture)
                            h5.font-weight-semi-bold.m-0.p-1 = category.name
                        -else
                            h5.font-weight-semi-bold.m-0 = category.name
                    