config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#home'
  resources :categories do 
    resources :products do
      collection do
        match 'search' => 'prdocuts#search', via: [:get, :post], as: :search
      end
    end
  end

  namespace :admin do
    resources :categories
    get "/dashboard", to: 'dashboard#index'
  end

  namespace :seller do
    resources :products
    get "/dashboard", to: 'dashboard#index'
    get "/dashboard/orders", to: 'dashboard#show'
  end
  get '/search', to: 'products#index'
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end

  resources :order_items, only: %i(create update destroy)
  resources :orders, only: %i(create show index)
  get '/cart', to: 'cart#show'

  get '/users/:username', to: 'profile#show', as: 'user'

  delete '/empty_cart', to: 'order_items#destroy_all'

  resources :reviews, only: %i(create edit update destroy) 
   
  post 'reviews_from_email', to: 'reviews#create_from_email'
  get '/reviews', to: 'reviews#new'

  mount Sidekiq::Web => '/sidekiq'


end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: %i(slugged history finders)
    validates_presence_of :price, :title, :stock, :categories
    validates :stock, numericality: { greater_than_or_equal_to: 0 }
    has_rich_text :description
    has_one_attached :product_picture
    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories
    has_many :reviews, dependent: :destroy

    belongs_to :seller, class_name: 'User'
    
    default_scope -> { where(deleted_at: nil) }
    scope :with_deleted, -> { unscope(where: :deleted_at) }
    scope :only_deleted, -> { with_deleted.where.not(deleted_at: nil) }
    
    scope :published, -> { where(published: true) }
    scope :onsale, -> { where(on_sale: true) }

    define_model_callbacks :soft_destroy

    def soft_destroy
        run_callbacks :soft_destroy do
            update_column("deleted_at", Time.now)
        end
    end

    def should_generate_new_friendly_id? #will change the slug if the name changed
        title_changed?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_category, only: :show
    before_action :set_product, only: :show
    before_action :set_new_review, only: :show
    def index        
        @category = Category.friendly.find(params[:category_id])
        @pagy, @products = pagy(@category.products.published.order(:title), items: 9)
    end
    def show 

        @category = @product.categories.first
        @review_count = @product.reviews.count
        if @review_count > 0
            @pagy, @reviews = pagy(@product.reviews.order("created_at DESC"), items: 5)
            @average_rating = (@product.reviews.collect { |review|  review.rating.to_i }.sum)/@review_count.to_f if @review_count > 0
        end
    end
    
    def search
        @q = Product.published.ransack(params[:q])
        @pagy, @products = pagy(@q.result(distinct: true), items: 21)
    end

    private 
    def set_product
        @product = Product.published.friendly.find(params[:id])
    end

    def set_category
        if params.has_key?(:category_id)
            @category = Category.friendly.find(params[:category_id])
        end
    end
    
    def set_new_review

        if user_signed_in?
             @order_item = current_user.order_items.find_by(product: @product, reviewed_at: nil)
        end
        @new_review = nil
        if !@order_item.nil?
            @new_review = @product.reviews.new(order_item_id: @order_item.id)
        end
    end

end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < Seller::BaseController
    before_action :authenticate_user! ## require user to login 
    before_action :set_product, only: [:show, :edit, :update, :destroy ]
    
    def show
        set_product
    end
    
    
    def new
        @product = Product.new
        authorize @product
    end

    def edit
        @product
        
        @category = @product.categories.first

    end

    def create
       
        @product = Product.new(product_params)
        @product.product_picture.attach(product_params[:product_picture])
        @product.seller = current_user
        authorize @product
        respond_to do |format|
            if @product.save
                format.html { redirect_to(request.referrer || seller_product_path(@product)) }
                flash[:notice] = "Product was successfully created." 
            else
                format.html { redirect_to(request.referrer) }
                flash[:notice] = "There was an error creating the product." 
            end
        end
    end

    def update
        
        respond_to do |format|
            if @product.update(ActiveModel::Type::Boolean.new.cast(product_params[:published]) ? product_params : product_params.merge(on_sale: false))
                format.html { redirect_to(request.referrer || seller_product_path(@product)) }
                flash[:notice] = "Product was successfully updated." 
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @product
        if @product.soft_destroy
             redirect_to seller_dashboard_path, notice: "Product was successfully destroyed."  
        else
            redirect_to @product, flash: { error: "Product could not be deleted" }
        end
    end

    private
    def set_product
        @product = authorize Product.friendly.find(params[:id])
        @category = @product.categories.first
    end

    
    def product_params

        if params[:id].present? && @product.published?
            params.require(:product).permit(:stock, :published, :on_sale)
        else            
            params.require(:product).permit(:title, :description, :price, :stock,
            :product_picture, :published, :on_sale, category_ids: [])
        end
    
    end
    
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/views/products/index.html.slim
.container-fluid
    .row.px-xl-5
        .col-lg-3.col-md-12
            .border-bottom.mb-4.pb-4
            .border-bottom.mb-4.pb-4
            .mb-5
        = render "products/shared/products", products: @products
    - if defined?(@category)
        .btn__group
            - if user_signed_in? and current_user.has_role? :admin
                = link_to 'Edit Category', edit_admin_category_path(@category), class: "btn btn__edit"
                = link_to 'Delete Category', admin_category_path(@category), method: :delete, class: "btn btn__delete"

= javascript_pack_tag "cart_quantity"

app/views/products/search.js.slim
| $("#search-results").html('
= j render('products/shared/products')
| ');

app/views/products/show.html.slim
.container-fluid
    h6.breadcrumbs.px-xl-5
        = link_to "Home", root_path
        |  > 
        = link_to @category.name, category_products_path(@category)
        |  > 
        = @product.title
    - if current_user == @product.seller
        a.px-xl-5.btn.edit-product data="#{@product.slug}" Edit product 

    .row.px-xl-5.py-5
        .col-lg-5.pb-5
            .carousel.slide#product-carousel 
                .carousel-inner.text-center
                    - if @product.product_picture.attached?
                        image.product__image src = url_for(@product.product_picture)
        .col-lg-7.product-page__info
            h3.font-weight-semi-bold = @product.title
            h5.product__vendor = @product.seller.first_name
            .d-flex.mb-3 = render 'reviews/partials/stars', reviews: @average_rating, review_count: @review_count


            h3.font-weight-semi-bold.mb-4 = number_to_currency @product.price
            h3.product__desc.bolder Description
            p.mb-4 =  @product.description.to_s
            .d-flex.justify-content-center
                = render "products/shared/order", product: @product

            .d-flex.pt-2
                p.font-weight-medium.mb-0.mr-2 Share on:
                .d-inline-flex
                    a.px-2 href=""
                        i.fa.fa-facebook
                    a.px-2 href=""
                        i.fa.fa-twitter
                    a.px-2 href=""
                        i.fa.fa-pinterest
    .row.px-xl-5
        .col-12.p-0 = render "reviews/partials/review_widget", reviews: @reviews, average_rating: @average_rating, review_count: @review_count, new_review: @new_review


= javascript_pack_tag "cart_quantity"